function compare_nii
subject={   'WT9',...
            'WT8',...
            'WT7',...
            'WT6',...
            'WT5',...
            'WT3',...
            'WT2',...
            'KO1',...
            'KO2',...
            'KO3',...
            'KO4',...
            'KO5',...
            'KO6',...
            'KO7',...
            'KO8',...
            };
for subj=1:numel(subject)
    
directory='/Volumes/SAMSUNG 1/MSc_PhD/DTI_Analysis/smoothed_allscans';
files=fuf([directory '/swr' subject{subj} '*_FA.nii'],'detail');
fig=figure;
slice4examination=25;
for i=1:numel(files)
    tmp=load_nii(files{i});
    data(:,:,:,i)=tmp.img;
    imagesc(data(:,:,slice4examination,i));
    saveas(fig,[subject{subj} '_' int2str(i) '.jpeg']);
end
data1=squeeze(data(:,:,slice4examination,:));
a1=make_nii(data1,[0.16 0.16 0.16],[0;0;0],16);
save_nii(a1,[subject{subj} '_QC.nii']);

close all
end
